# Use postgres/example user/password credentials
# Frontend image isn't real for now
version: '3.1'

services:

    frontend:
      build: .
      env_file:
        - .env
      ports:
        - 5000:5000
