# Use postgres/example user/password credentials
# Frontend image isn't real for now
version: '3.1'

services:

    frontend:
      image: dariaveselkova/ecatalog-frontend:1.0.0
      env_file:
        - .env
      ports:
        - 5000:5000
